language: python
sudo: false

env:
  global:
    # Doctr deploy key for regro/cf-graph
    - secure: "SiGX99CpSLIHQXcOR8RN3JfL9pdyps1kFISSaaICFOJ65Wp+C5ERWzqZMOr7NlmTijJmCQ4DzGi9h1t+zYWgg+l2XsUXLS+4SDI5SZMCmbP5vHiP2qxnWEiCPTaZrXMNeGcD4yW1KvwxnrRIcyX4JDz2EP4cLKS0laj3kpGTrYPVx2wFrX8/V78SPIZ9S2m1aSOmOtEvyaj1gOdazxGXjLyZ43FbrhwKILweVd8wgsKS4GKsgQIXDRxk4713f32SMOzav+xI6IzHxaoo3RQu3NQQfoeks73/hfxdNyr76fggimXKUPo5tS84W5rU6fwhhZU/ojSxJIMnGcZSRGpmk86nd3l6+jSqU6txinwO5ROL3wvu0o06cY17WAUzPfF/z5Oo5sNbWeuj9Idp9ske4wfWx17q0Z/jkOBiRXYGetjdQTwRlRrqf9R7hja6QGm0giSgXTMGNMyWsI+YIWAZcl5vYBuPCFGc8RUfuRz4zL34oN/4pa7rewkamkNlgTxx9V+lBj46+tNMlrhWhF97z+p+Bpl1zauGxCxCSEGxeWSNyIHgu4z4CKm9q4LG5G201QC71P+6i9Zbo0xcX5PnZi/V1Smky8yQJ4F791GJfSsCMfo98FIQJ7ZoLFyB2YP2dLH538QXL51IKGz8E8PMzZKDpVi+bOzj6iN7e9Qw0LM="

python:
  - 3.6
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda update conda --yes
  - conda config --add channels conda-forge


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda install python=$TRAVIS_PYTHON_VERSION
  - git clone https://github.com/regro/cf-graph.git
  - cd cf-graph
  - conda install --file requirements/run

script:
  - set -e
  - python 03-auto_tick.xsh
  - conda install doctr
  - doctr deploy --token --built-docs . --deploy-repo regro/cf-graph --deploy-branch-name master .
